<a href="https://colab.research.google.com/github/lawviet123/CS114.K21/blob/master/Round3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import thư viện

In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

# **1. Cách lấy dữ liệu.**

# ***Tải dữ liệu lên bằng dòng lệnh : time_df = pd.read_csv('url', names=["size", "time"]) ***

In [0]:
url='http://cs.uit.edu.vn/data2.txt'
time_df = pd.read_csv(url, names=["size", "time"])
size = time_df['size'].astype(float)

size_n2 = pow(size, 2)
size_log = size * np.log2(size)

time_df['size_n2'] = size_n2
time_df['size_log'] = size_log
column_names = ['size', 'size_n2', 'size_log', 'time']
pr_df = time_df.reindex(columns=column_names)

data = pr_df[['size', 'size_n2', 'size_log']].values
labels = pr_df['time'].values
print(pr_df.head(5))

      size       size_n2      size_log      time
0  6083695  3.701134e+13  1.371053e+08  0.521842
1  1954367  3.819550e+12  4.084289e+07  0.152648
2  3734185  1.394414e+13  8.152608e+07  0.298548
3  5839301  3.409744e+13  1.312521e+08  0.460480
4  6343427  4.023907e+13  1.433413e+08  0.527977


# **2. Chọn model là linear Regression.**

# **Chia thành 80% để train và 20% để test**

In [0]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=0)
print(X_test[:5])

[[2.66162600e+06 7.08425296e+12 5.68094165e+07]
 [7.54827800e+06 5.69765008e+13 1.72460913e+08]
 [2.31665100e+06 5.36687186e+12 4.89823636e+07]
 [1.97702800e+06 3.90863971e+12 4.13493466e+07]
 [6.33747800e+06 4.01636274e+13 1.43198341e+08]]


In [0]:
lire = LinearRegression()
lire.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
y_pred = lire.predict(X_test)
print('weight: ', lire.coef_)
print('bias: ',lire.intercept_)

weight:  [ 4.64869785e-09 -1.34867177e-17  3.40724362e-09]
bias:  0.0002330963442465639


# **4.Khả năng dự đoán của ứng dụng là tốt vì mean squared error = 0.00**

# **Khả năng dự đoán tốt hay không dựa vào Mean squared error**

In [0]:
print(mean_squared_error(y_test, y_pred))
print('Mean squared error: %.2f' % mean_squared_error(y_test, y_pred))

print('Coefficient of determination: %.2f' % r2_score(y_test, y_pred))

0.00013063874994216244
Mean squared error: 0.00
Coefficient of determination: 1.00


# **Xây dựng model mới**

# Ta sẽ tăng thêm 2 features size**2 và size.log(size) 

In [19]:
url ='http://cs.uit.edu.vn/data3.txt'
ime_df = pd.read_csv(url, names=["size", "time"])
size = time_df['size'].astype(float)

size_n2 = pow(size, 2)
size_log = size * np.log2(size)

time_df['size_n2'] = size_n2
time_df['size_log'] = size_log
column_names = ['size', 'size_n2', 'size_log', 'time']
pr_df = time_df.reindex(columns=column_names)

data = pr_df[['size', 'size_n2', 'size_log']].values
labels = pr_df['time'].values
print(pr_df.head(5))

       size       size_n2      size_log     time
0  37837612  1.431685e+15  9.524982e+08  4.12166
1  37395246  1.398404e+15  9.407280e+08  3.92089
2  36610827  1.340353e+15  9.198751e+08  3.21540
3  29555651  8.735365e+14  7.334805e+08  2.54506
4  25928216  6.722724e+14  6.385606e+08  2.21831


# **Ta sử dung tăng số features**

In [20]:
size = time_df['size'].astype(float)

size_n2 = pow(size, 2)
size_log = size * np.log2(size)

time_df['size_n2'] = size_n2
time_df['size_log'] = size_log
column_names = ['size', 'size_n2', 'size_log', 'time']
pr_df = time_df.reindex(columns=column_names)

data = pr_df[['size', 'size_n2', 'size_log']].values
labels = pr_df['time'].values
print(pr_df.head(5))

       size       size_n2      size_log     time
0  37837612  1.431685e+15  9.524982e+08  4.12166
1  37395246  1.398404e+15  9.407280e+08  3.92089
2  36610827  1.340353e+15  9.198751e+08  3.21540
3  29555651  8.735365e+14  7.334805e+08  2.54506
4  25928216  6.722724e+14  6.385606e+08  2.21831


# **Chia dữ liệu thành huấn luyện 80% và test 20%**

In [21]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=0)
print(X_test[:5])

[[3.90274990e+07 1.52314568e+15 9.84194989e+08]
 [2.67671810e+07 7.16481979e+14 6.60452403e+08]
 [3.67649930e+07 1.35166471e+15 9.23971531e+08]
 [2.92873050e+07 8.57746234e+14 7.26435639e+08]
 [3.43621860e+07 1.18075983e+15 8.60233908e+08]]


In [22]:
# choose model Linearn Regression
lire = LinearRegression()
lire.fit(X_train, y_train)
y_pred = lire.predict(X_test)
print('Mean squared error: ' , mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' % r2_score(y_test, y_pred))

Mean squared error:  0.002978417253932674
Coefficient of determination: 0.99
